services:
  AgentCanvas:
    image: ghcr.io/mai0313/agentcanvas:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command:
      - yarn
      # - preview
      - dev
      - --host=0.0.0.0
      - --port=3000
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env
    pull_policy: always
    restart: always
